<p>It is as if there is no <code>try</code>/<code>catch</code> statement. The exception is thrown to the calling method.</p>