<p>The above code is an example of a nesting exception. When the <code>Exception</code> is thrown, by passing in the <code>ClassCastException</code> object reference as a parameter, the <code>ClassCastException</code> is nested in the newly created <code>Exception</code>, its stack-trace is appended together. When the <code>Exception</code> is caught, its stack-trace contains the original <code>ClassCastException</code>'s stack-trace.</p>